// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw4wbBDGLjlnyMrIzpnzVjxPjo2JHykN4',
    appId: '1:536879979202:web:c28a843a3cd257cfa7795b',
    messagingSenderId: '536879979202',
    projectId: 'my-eccm-project',
    authDomain: 'my-eccm-project.firebaseapp.com',
    storageBucket: 'my-eccm-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRAYhJGmVIr-4uwHgqfnHWYBKsPUcZrJs',
    appId: '1:536879979202:android:7b1e1802ba3a9715a7795b',
    messagingSenderId: '536879979202',
    projectId: 'my-eccm-project',
    storageBucket: 'my-eccm-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxJaGWvSMTZvWuxfDuMl_Fu2HNd7T_ygY',
    appId: '1:536879979202:ios:c1eff58fa3296c5ba7795b',
    messagingSenderId: '536879979202',
    projectId: 'my-eccm-project',
    storageBucket: 'my-eccm-project.appspot.com',
    iosClientId: '536879979202-oendtppj4nmlhmh83o8ma9fg3jksu347.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxJaGWvSMTZvWuxfDuMl_Fu2HNd7T_ygY',
    appId: '1:536879979202:ios:c1eff58fa3296c5ba7795b',
    messagingSenderId: '536879979202',
    projectId: 'my-eccm-project',
    storageBucket: 'my-eccm-project.appspot.com',
    iosClientId: '536879979202-oendtppj4nmlhmh83o8ma9fg3jksu347.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
